#pragma once


#include <fltKernel.h>

#define READ_BUFFER_TAG					'rbtg'
#define WRITE_BUFFER_TAG				'wbtg'
#define FILE_NAME_BUFFER_TAG			'fnbt'
#define SHARE_ACCESS_TAG				'sast'
#define DOS_NAME_BUFFER_TAG				'dnbt'

#define POC_TARGET_FILE_EXTENSION		0xFFFF7777
#define POC_STATUS_AES_INIT_FAILED		0xFFFF7776
#define POC_FILE_HAS_ENCRYPTION_HEADER	0xFFFF7775
#define POC_FILE_HAS_ENCRYPTION_TAILER	0xFFFF7774
#define POC_TO_APPEND_ENCRYPTION_TAILER	0xFFFF7773
#define POC_BEING_APPEND_ENC_TAILER		0xFFFF7772
#define POC_IS_IRRELEVENT_PROCESS		0xFFFF7771
#define POC_IS_WORD_BACK_UP_FILE		0xFFFF7770
#define POC_TAILER_WRONG_FILE_NAME		0xFFFF776F
#define POC_IS_TARGET_FILE_EXTENSION	0xFFFF776E
#define POC_IRRELEVENT_FILE_EXTENSION	0xFFFF776D
#define POC_IS_UNAUTHORIZED_PROCESS		0xFFFF776C
#define POC_IS_AUTHORIZED_PROCESS		0xFFFF776B
#define POC_IS_IRRELEVENT_PATH			0xFFFF776A
#define POC_FILE_IS_PLAINTEXT			0xFFFF7769
#define POC_FILE_IS_CIPHERTEXT			0xFFFF7768
#define POC_BEING_DIRECT_ENCRYPTING		0xFFFF7767
#define POC_RENAME_TO_ENCRYPT			0xFFFF7766


#define POC_MAX_NAME_LENGTH				320

#define POC_ENCRYPTION_HEADER_FLAG		"FOKS-TROT"
#define POC_ENCRYPTION_HEADER_EA_TYPE	"AES-128 ECB"

extern PFLT_FILTER gFilterHandle;

#define PTDBG_TRACE_ROUTINES            0x00000001
#define PTDBG_TRACE_OPERATION_STATUS    0x00000002

const static ULONG gTraceFlags = 0;


#define PT_DBG_PRINT( _dbgLevel, _string )          \
    (FlagOn(gTraceFlags,(_dbgLevel)) ?              \
        DbgPrint _string :                          \
        ((int)0))

